name: Pull Prusaslicer release and upload artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of prusaslicer to pull (X.X.X)'
        required: true
        type: string

defaults:
  run:
    shell: bash
    working-directory: .
        

jobs:
  prusaslicer:
    name: Pull-Assets
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.9
        name: Pull Linux Build
        with:
          repository: "prusa3d/PrusaSlicer"
          tag: "version_${{inputs.version}}"
          fileName: "PrusaSlicer-${{inputs.version}}+linux-arm64*.tar.bz2"
          out-file-path: "prusaslicer-linux"
          extract: true
      - uses: robinraju/release-downloader@v1.9
        name: Pull Windows Build
        with:
          repository: "prusa3d/PrusaSlicer"
          tag: "version_${{inputs.version}}"
          fileName: "PrusaSlicer-${{inputs.version}}+win64*.zip"
          out-file-path: "prusaslicer-windows"
          extract: true
      - uses: robinraju/release-downloader@v1.9
        name: Pull MacOS DMG
        with:
          repository: "prusa3d/PrusaSlicer"
          tag: "version_${{inputs.version}}"
          fileName: "PrusaSlicer-${{inputs.version}}+MacOS*.dmg"
          out-file-path: "prusaslicer.dmg"
          extract: true
      - name: Extract DMG
        if: false
        run: |
          ls
          echo "Install 7z"
          sudo apt-get install -y p7zip-full p7zip-rar
          echo "Installed 7z"
          ls
          echo "Running 7z"
          pwd

      - uses: actions/upload-artifact@v3
        with:
          name: prusaslicer-linux
          path: prusaslicer-linux
      - uses: actions/upload-artifact@v3
        with:
          name: prusaslicer-windows
          path: prusaslicer-windows
      - uses: actions/upload-artifact@v3
        with:
          name: prusaslicer-macos
          path: prusaslicer.dmg
