name: Pull Prusaslicer release and upload artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of prusaslicer to pull (X.X.X)'
        required: true
        type: string

defaults:
  run:
    shell: bash
    working-directory: .
        

jobs:
  prusaslicer:
    name: Pull-Assets
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.8
        name: Pull All Release Assets
        with:
          repository: "prusa3d/PrusaSlicer"
          tag: "version_${{inputs.version}}"
          out-file-path: "prusaslicer-assets"
      - name: Extract Linux files
        run: |
          ls *
          echo "Finding asset tar for linux arm64"
          cd prusaslicer-assets
          for f in PrusaSlicer-${{inputs.version}}+linux-arm64*.tar.bz2; do mv "$f" "prusaslicer-linux.tar.bz2" ; done
          cd ..
          mv prusaslicer-assets/prusaslicer-linux.tar.bz2 prusaslicer-linux.tar.bz2
          echo "Unzipping tar asset for linux arm64"
          tar -xf prusaslicer-linux.tar.bz2          
          echo "Renaming asset"
          for f in PrusaSlicer-${{inputs.version}}+linux-arm64*; do mv "$f" "prusaslicer-linux" ; done
          ls *
      - name: Extract Windows files
        run: |
          ls *
          echo "Finding asset tar for windows 64-bit"
          cd prusaslicer-assets
          for f in PrusaSlicer-${{inputs.version}}+win64*.zip; do mv "$f" "prusaslicer-windows.zip" ; done
          cd ..
          mv prusaslicer-assets/prusaslicer-windows.zip prusaslicer-windows.zip
          echo "Unzipping windows asset"
          7z x prusaslicer-windows.zip
          echo "Renaming asset"
          for f in PrusaSlicer-${{inputs.version}}+win64*; do mv "$f" "prusaslicer-windows" ; done
          ls *
      - name: Extract DMG Files
        run: |
          ls *
          ls *
          cd prusaslicer-assets
          for f in PrusaSlicer-${{inputs.version}}+MacOS*.dmg; do mv "$f" "prusaslicer-mac.dmg" ; done
          cd ..
          mv prusaslicer-assets/prusaslicer-mac.dmg prusaslicer-mac.dmg
          7z x prusaslicer-mac.dmg prusaslicer-mac
          cd prusaslicer-mac
          ls *

      - uses: actions/upload-artifact@v4
        with:
          name: prusaslicer-linux
          path: ${{ github.workspace }}/prusaslicer-linux
      - uses: actions/upload-artifact@v4
        with:
          name: prusaslicer-windows
          path: ${{ github.workspace }}/prusaslicer-windows
      - uses: actions/upload-artifact@v4
        with:
          name: prusaslicer-macos
          path: ${{ github.workspace }}/prusaslicer.dmg
