name: Pull Prusaslicer release and upload artifacts

on:
  pull_request:

jobs:
  checkversion:
    name: Check Version was updated
    runs-on: ubuntu-latest
    steps:
      - name: Check if version file was updated
        id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            version:
              - version.txt
      - name: Run step if test file(s) change
        if: steps.changed-files-yaml.outputs.version_any_changed == 'false'  
        run: |
            echo "Did not update version.txt"
            exit 1